const ADDRESS_DATA = [
  {
    "Business Name": "Darryl's Corner Bar and Kitchen",
    "Address": "604 Columbus Ave, Boston, Ma",
    "Neighborhood": "South End",
    "Type of Food": "BBQ Joint",
    "Website": "http://dcbkboston.com/",
    "Latitude": 42.339767,
    "Longitude": -71.0824,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 604,
    "Street": "Columbus Ave",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2118,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "Teranga Restaurant",
    "Address": "1746 Washington Street, Boston, Ma",
    "Neighborhood": "South End",
    "Type of Food": "African Food",
    "Website": "http://terangaboston.com/",
    "Latitude": 42.336477,
    "Longitude": -71.076531,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 1746,
    "Street": "Washington St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2118,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "La Fabrica Central",
    "Address": "450 Massachusetts Ave, Cambridge, Ma",
    "Neighborhood": "Cambridge",
    "Type of Food": "Caribbean Food",
    "Website": "https://www.lafabricacentral.com/",
    "Latitude": 42.363484,
    "Longitude": -71.101101,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 450,
    "Street": "Massachusetts Ave",
    "City": "Cambridge",
    "State": "MA",
    "County": "Middlesex County",
    "Zip": 2139,
    "Country": "US",
    "Source": "City of Cambridge"
  },
  {
    "Business Name": "Savvor Restaurant",
    "Address": "180 Lincoln Street, Boston, MA 02111",
    "Neighborhood": "Finance District",
    "Type of Food": "Haitian",
    "Website": "https://www.savvorbostonlounge.com/",
    "Latitude": 42.350537,
    "Longitude": -71.058441,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 180,
    "Street": "Lincoln St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2111,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "Restaurante Cesaria",
    "Address": "266 Bowdoin Street, Boston, Ma",
    "Neighborhood": "North Dorchester",
    "Type of Food": "Cape Verdean/African",
    "Website": "https://www.facebook.com/RestaurantCesaria/",
    "Latitude": 42.30692,
    "Longitude": -71.06667,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 266,
    "Street": "Bowdoin St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2125,
    "Country": "US",
    "Source": "City of Boston"
  },
  {
    "Business Name": "Restaurant Laura",
    "Address": "688 Columbia Rd, Dorchester, MA 02125",
    "Neighborhood": "North Dorchester",
    "Type of Food": "Cape Verdean/African",
    "Website": "https://www.facebook.com/pages/category/Family-Style-Restaurant/Restaurant-Laura-347785340882/",
    "Latitude": 42.320097,
    "Longitude": -71.062641,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 688,
    "Street": "Columbia Rd",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2125,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "BRED",
    "Address": "2255 Dorchester Ave Boston, MA 02124",
    "Neighborhood": "South Dorchester",
    "Type of Food": "Burger Joint",
    "Website": "http://www.bredgourmet.com/",
    "Latitude": 42.273407,
    "Longitude": -71.067951,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 2255,
    "Street": "Dorchester Ave",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2124,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "ZAZ Restaurant",
    "Address": "1238 River St, Hyde Park, MA 02136",
    "Neighborhood": "Hyde Park",
    "Type of Food": "Caribbean",
    "Website": "http://www.zazrestaurant.com/",
    "Latitude": 42.255807,
    "Longitude": -71.122991,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 1238,
    "Street": "River St",
    "City": "Hyde Park",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2136,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "MIDA Restaurant",
    "Address": "782 Tremont St, Boston, MA 02118",
    "Neighborhood": "South End",
    "Type of Food": "Italian",
    "Website": "http://www.midaboston.com",
    "Latitude": 42.339047,
    "Longitude": -71.080431,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 782,
    "Street": "Tremont St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2118,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "Churrascaria Vulc̣o",
    "Address": "203 Adams St, Boston, MA 02122",
    "Neighborhood": "South Dorchester",
    "Type of Food": "Cape Verdean/Portuguese",
    "Website": "http://www.churrascariavulcao.com/",
    "Latitude": 42.301898,
    "Longitude": -71.060211,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 203,
    "Street": "Adams St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2122,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "Fort Hill Bar & Grill",
    "Address": "2805 Washington St, Boston, MA 02119",
    "Neighborhood": "Roxbury",
    "Type of Food": "Dominican/American",
    "Website": "https://www.facebook.com/forthillbarandgrill/",
    "Latitude": 42.321426,
    "Longitude": -71.092089,
    "Accuracy Score": 1,
    "Accuracy Type": "range_interpolation",
    "Number": 2805,
    "Street": "Washington St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2119,
    "Country": "US",
    "Source": "TIGER/Line� dataset from the US Census Bureau"
  },
  {
    "Business Name": "Suyya Joint",
    "Address": "185 Dudley St #2, Roxbury, MA 02119",
    "Neighborhood": "Roxbury",
    "Type of Food": "Nigerian ",
    "Website": "https://suyajoint.com/",
    "Latitude": 42.32832,
    "Longitude": -71.08196,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 185,
    "Street": "Dudley St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2119,
    "Country": "US",
    "Source": "City of Boston"
  },
  {
    "Business Name": "Dona Habana",
    "Address": "811 Massachusetts Ave, Boston, MA 02118",
    "Neighborhood": "South End",
    "Type of Food": "Cuban",
    "Website": "http://donahabanarestaurant.com/",
    "Latitude": 42.332703,
    "Longitude": -71.072923,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop",
    "Number": 811,
    "Street": "Massachusetts Ave",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2119,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "Addis Red Sea",
    "Address": "544 Tremont St, Boston, MA 02116",
    "Neighborhood": "South End",
    "Type of Food": "Ethiopian",
    "Website": "http://www.addisredsea.com/",
    "Latitude": 42.344027,
    "Longitude": -71.071051,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop",
    "Number": 544,
    "Street": "Tremont St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2118,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "The Coast Cafe",
    "Address": "233 River St, Cambridge, MA 02139",
    "Neighborhood": "Cambridge",
    "Type of Food": "South American",
    "Website": "http://www.coastsoulcafe.com/",
    "Latitude": 42.363012,
    "Longitude": -71.111597,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 233,
    "Street": "River St",
    "City": "Cambridge",
    "State": "MA",
    "County": "Middlesex County",
    "Zip": 2139,
    "Country": "US",
    "Source": "City of Cambridge"
  },
  {
    "Business Name": "Wally's Jazz Cafe",
    "Address": "427 Massachusetts Ave, Boston, MA 02118",
    "Neighborhood": "South End",
    "Type of Food": "Jazz Bar",
    "Website": "http://wallyscafe.com/",
    "Latitude": 42.340697,
    "Longitude": -71.082291,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 427,
    "Street": "Massachusetts Ave",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2118,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "Slade's Bar and Grille ",
    "Address": "958 Tremont St, Boston, MA 02120",
    "Neighborhood": "South End",
    "Type of Food": "Southern ",
    "Website": "https://www.sladesbarandgrill.com/",
    "Latitude": 42.337256,
    "Longitude": -71.083617,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 958,
    "Street": "Tremont St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2120,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "Rock CIty Pizza",
    "Address": "568 Cambridge St, Allston, MA 02134",
    "Neighborhood": "Allston",
    "Type of Food": "Pizzeria",
    "Website": "https://rockcitypizzeria.com/",
    "Latitude": 42.352312,
    "Longitude": -71.14044,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 568,
    "Street": "Cambridge St",
    "City": "Allston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2134,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "Ashur Restaurant",
    "Address": "291 Roxbury St, Roxbury, MA 02119",
    "Neighborhood": "Roxbury",
    "Type of Food": "Somali",
    "Website": "https://www.bostonmagazine.com/best-of-boston/2015/ashur-restaurant/",
    "Latitude": 42.330427,
    "Longitude": -71.094301,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 291,
    "Street": "Roxbury St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2119,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "Asmara Restaurant",
    "Address": "739 Massachusetts Ave, Cambridge, MA 02139",
    "Neighborhood": "Cambridge",
    "Type of Food": "Ethiopian",
    "Website": "http://www.asmararestaurantboston.com/",
    "Latitude": 42.366458,
    "Longitude": -71.105164,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 739,
    "Street": "Massachusetts Ave",
    "City": "Cambridge",
    "State": "MA",
    "County": "Middlesex County",
    "Zip": 2139,
    "Country": "US",
    "Source": "City of Cambridge"
  },
  {
    "Business Name": "Flames",
    "Address": "469 Blue Hill Avenue, Dorchester, MA 02121",
    "Neighborhood": "Dorchester-Grove Hall",
    "Type of Food": "Jamaican",
    "Latitude": 42.309036,
    "Longitude": -71.083258,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 469,
    "Street": "Blue Hill Ave",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2121,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "Flames II",
    "Address": "746 Huntington Ave, Boston, MA 02115",
    "Neighborhood": "Mission Hill",
    "Type of Food": "Jamaican",
    "Website": "https://www.zagat.com/r/flames-restaurant-inc-boston1",
    "Latitude": 42.333647,
    "Longitude": -71.105491,
    "Accuracy Score": 0.9,
    "Accuracy Type": "rooftop",
    "Number": 746,
    "Street": "Huntington Ave",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2120,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  },
  {
    "Business Name": "The Beehive",
    "Address": "541 Tremont St, Boston, MA 02116",
    "Neighborhood": "South End",
    "Type of Food": "American",
    "Website": "https://www.beehiveboston.com/",
    "Latitude": 42.344716,
    "Longitude": -71.071388,
    "Accuracy Score": 1,
    "Accuracy Type": "rooftop",
    "Number": 541,
    "Street": "Tremont St",
    "City": "Boston",
    "State": "MA",
    "County": "Suffolk County",
    "Zip": 2116,
    "Country": "US",
    "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
  }
];