
const ADDRESS_DATA = [
 {
   "Name": "White Stadium",
   "Address": "450 Walnut Ave, Boston, MA '02130",
   "Neighborhood": "JP/Roxbury",
   "Description": "Was home to Black Power rallies in the 60s and 70s",
   "Link to Description": "",
   "Link to Image": "http://jamaicaplaingazette.com/wp-content/uploads/2013/07/White-300x225.jpg",
   "Additional Resources": "",
   "Latitude": 42.311698,
   "Longitude": -71.097411,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": "450",
   "Street": "Walnut Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Donna Summer Childhood Home",
   "Address": "16 Parker Hill Ave Boston, MA '02120",
   "Neighborhood": "Mission Hill",
   "Description": "Donna Summers childhood family home",
   "Link to Description": "http://missionhillgazette.com/2012/06/01/mission-hill-remembers-its-queen-of-disco/",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.332507,
   "Longitude": -71.109331,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "16",
   "Street": "Parker Hill Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2115,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Malcom X Home",
   "Address": "72 Dale St Roxbury, MA '02119",
   "Neighborhood": "Roxbury",
   "Description": "Malcolm X's childhood Boston home",
   "Link to Description": "http://historicboston.org/portfolio_page/malcolm-x-house/",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.32138,
   "Longitude": -71.08644,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "72",
   "Street": "Dale St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "City of Boston"
 },
 {
   "Name": "Boston Courthouse ",
   "Address": "26 Court Street Boston, MA '02108",
   "Neighborhood": "Financial District",
   "Description": "Shadrach Minkins escaped trial for the Fugitive Slave Act of 1850",
   "Link to Description": "",
   "Link to Image": "http://www.wbur.org/news/2015/04/08/boston-old-courthouse-jail-court-street",
   "Additional Resources": "",
   "Latitude": 42.358637,
   "Longitude": -71.059011,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "26",
   "Street": "Court St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2108,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Zipporah Potter Atkins house marker",
   "Address": "Rose Kennedy Greenway",
   "Neighborhood": "North End",
   "Description": "Boston's first African American woman homeowner (in the 1700s)",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 36.327813,
   "Longitude": -90.182485,
   "Accuracy Score": 1,
   "Accuracy Type": "place",
   "Number": "",
   "Street": "",
   "City": "Greenway",
   "State": "AR",
   "County": "Clay County",
   "Zip": 72430,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Black Panther Party Boston Office",
   "Address": "375 Blue Hill Ave. Roxbury, MA '02119",
   "Neighborhood": "Roxbury",
   "Description": "Black Panther Party Boston chapter headquarters",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.3118,
   "Longitude": -71.081061,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "375",
   "Street": "Blue Hill Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2121,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Alvah Kittredge House",
   "Address": "10 Linwood Street Roxbury, MA '02119",
   "Neighborhood": "Roxbury",
   "Description": "Home to Roxbury Action Program for some time in the 1960s-70s",
   "Link to Description": "http://archive.boston.com/business/articles/2011/07/16/project_to_restore_historic_roxbury_site/",
   "Link to Image": "",
   "Additional Resources": "http://scua.library.umass.edu/umarmot/roxbury-action-program/",
   "Latitude": 42.327787,
   "Longitude": -71.092963,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "10",
   "Street": "Linwood St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "William Carter Playground",
   "Address": "396 Northampton St, Boston, MA '02118",
   "Neighborhood": "Roxbury",
   "Description": "First public park in Boston named for an African American",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.340568,
   "Longitude": -71.083841,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "396",
   "Street": "Northampton St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Combahee River Collective Headquarters",
   "Address": "46 Pleasant Street Cambridge, MA '02139",
   "Neighborhood": "Cambridge",
   "Description": "Combahee River Collective Headquarters",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.363738,
   "Longitude": -71.108426,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "46",
   "Street": "Pleasant St",
   "City": "Cambridge",
   "State": "MA",
   "County": "Middlesex County",
   "Zip": 2139,
   "Country": "US",
   "Source": "City of Cambridge"
 },
 {
   "Name": "Robert Gould Shaw and 54th Regiment Memorial",
   "Address": "Beacon and Park Streets, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "Robert Gould Shaw and 54th Regiment Memorial",
   "Link to Description": "http://maah.org/site1.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.358336,
   "Longitude": -71.061509,
   "Accuracy Score": 0.86,
   "Accuracy Type": "intersection",
   "Number": "",
   "Street": "Beacon St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2108,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "George Middleton House",
   "Address": "5-7 Pinckney Street, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "George Middleton House",
   "Link to Description": "http://maah.org/site2.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.358927,
   "Longitude": -71.065321,
   "Accuracy Score": 0.8,
   "Accuracy Type": "rooftop",
   "Number": "5",
   "Street": "Pinckney St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "The Phillips School",
   "Address": "Anderson and Pinckney Streets, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "The Phillips School",
   "Link to Description": "http://maah.org/site3.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.35908,
   "Longitude": -71.067683,
   "Accuracy Score": 0.88,
   "Accuracy Type": "intersection",
   "Number": "",
   "Street": "Anderson St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "John J. Smith House",
   "Address": "86 Pinckney Street, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "John J. Smith House",
   "Link to Description": "http://maah.org/site4.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.358757,
   "Longitude": -71.069701,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "86",
   "Street": "Pinckney St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2108,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Charles Street Meeting House",
   "Address": "Mt. Vernon and Charles Street, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "Charles Street Meeting House",
   "Link to Description": "http://maah.org/site5.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.370866,
   "Longitude": -71.061028,
   "Accuracy Score": 0.27,
   "Accuracy Type": "intersection",
   "Number": "",
   "Street": "Charles River Ave",
   "City": "Charlestown",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2129,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Lewis and Harriet Hayden House",
   "Address": "66 Phillips Street, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "Lewis and Harriet Hayden House",
   "Link to Description": "http://maah.org/site6.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.360197,
   "Longitude": -71.069041,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "66",
   "Street": "Phillips St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "John Coburn House",
   "Address": "2 Phillips Street, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "John Coburn House",
   "Link to Description": "http://maah.org/site7.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.360247,
   "Longitude": -71.066491,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "2",
   "Street": "Phillips St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Smith Court Residences",
   "Address": "3 Smith Court, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "aka James Scott and William C. Nell House",
   "Link to Description": "http://maah.org/site8.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.360147,
   "Longitude": -71.065371,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "3",
   "Street": "Smith Ct",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Smith Court Residences",
   "Address": "5 Smith Court, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "Smith Court Residences",
   "Link to Description": "http://maah.org/site8.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.360127,
   "Longitude": -71.065531,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "5",
   "Street": "Smith Ct",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Smith Court Residences",
   "Address": "7 Smith Court, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "Smith Court Residences",
   "Link to Description": "http://maah.org/site8.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.360126,
   "Longitude": -71.065593,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "7",
   "Street": "Smith Ct",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Smith Court Residences",
   "Address": "7A Smith Court, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "Smith Court Residences",
   "Link to Description": "http://maah.org/site8.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.360195,
   "Longitude": -71.065601,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "7 A",
   "Street": "Smith Ct",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "City of Boston"
 },
 {
   "Name": "Smith Court Residences",
   "Address": "4 Smith Court, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "Smith Court Residences",
   "Link to Description": "http://maah.org/site8.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.360007,
   "Longitude": -71.065271,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "4",
   "Street": "Smith Ct",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Smith Court Residences",
   "Address": "2 Smith Court, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "Smith Court Residences",
   "Link to Description": "http://maah.org/site8.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.359967,
   "Longitude": -71.065581,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "2",
   "Street": "Smith Ct",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Abiel Smith School",
   "Address": "46 Joy Street, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "The first building in the country constructed specifically as a public school for black children",
   "Link to Description": "http://maah.org/site13.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.360007,
   "Longitude": -71.065221,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "46",
   "Street": "Joy St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "The African Meeting House",
   "Address": "46 Joy Street, Boston, MA 02108",
   "Neighborhood": "Beacon Hill",
   "Description": "The African Meeting House",
   "Link to Description": "http://maah.org/site14.htm",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.360007,
   "Longitude": -71.065221,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "46",
   "Street": "Joy St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2114,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Crispus Attucks Memorial",
   "Address": "139 Tremont Street, Boston, MA 02111",
   "Neighborhood": "Downtown",
   "Description": "Crispus Attucks Memorial",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.355444,
   "Longitude": -71.063828,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "139",
   "Street": "Tremont St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2108,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "William Monroe Trotter House",
   "Address": "97 Sawyer Avenue, Dorchester, MA 02124",
   "Neighborhood": "Dorchester",
   "Description": "William Monroe Trotter House",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.313037,
   "Longitude": -71.062781,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "97",
   "Street": "Sawyer Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2125,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "National Center of Afro-American Artists",
   "Address": "300 Walnut Avenue, Roxbury, MA 02119",
   "Neighborhood": "Roxbury",
   "Description": "National Center of Afro-American Artists",
   "Link to Description": "http://ncaaa.org/",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.316784,
   "Longitude": -71.092025,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": "300",
   "Street": "Walnut Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "William E. Carter Playground",
   "Address": "369 Northampton Street 02118",
   "Neighborhood": "Roxbury",
   "Description": "William E. Carter Playground",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.340463,
   "Longitude": -71.082773,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": "369",
   "Street": "Northampton St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Reggie Lewis Center",
   "Address": "1350 Tremont Street, Roxbury Crossing, MA 02120",
   "Neighborhood": "Roxbury Crossing",
   "Description": "Reggie Lewis Center",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.331823,
   "Longitude": -71.093092,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "1350",
   "Street": "Tremont St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2120,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Forest Hills Cemetary",
   "Address": "95 Forest Hills Ave. Jamaica Plain, MA 02130",
   "Neighborhood": "Jamaica Plain",
   "Description": "Forest Hills Cemetary",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.298358,
   "Longitude": -71.108056,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "95",
   "Street": "Forest Hills Ave",
   "City": "Jamaica Plain",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2130,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Copp's Hill Burying Ground",
   "Address": "Hull Street, Boston, MA 02113",
   "Neighborhood": "North End",
   "Description": "Copp's Hill Burying Ground",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.366985,
   "Longitude": -71.056299,
   "Accuracy Score": 1,
   "Accuracy Type": "street_center",
   "Number": "",
   "Street": "Hull St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2113,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Granary Burying Ground",
   "Address": "Tremont Street and Broomfield Street, Boston, MA 02108",
   "Neighborhood": "Downtown",
   "Description": "Gravesite of Crispus Attucks",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.356845,
   "Longitude": -71.060391,
   "Accuracy Score": 0.93,
   "Accuracy Type": "intersection",
   "Number": "",
   "Street": "Bromfield St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2108,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Most Worshipful Prince Hall Grand Lodge",
   "Address": "24 Washington Street, Dorchester, MA 02121",
   "Neighborhood": "Dorchester",
   "Description": "Most Worshipful Prince Hall Grand Lodge",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.307731,
   "Longitude": -71.082339,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "24",
   "Street": "Washington St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2121,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Maria Louise Baldwin House",
   "Address": "196 Prospect Street Cambridge, MA 02139",
   "Neighborhood": "Cambridge",
   "Description": "Maria Louise Baldwin House",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.370173,
   "Longitude": -71.100282,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "196",
   "Street": "Prospect St",
   "City": "Cambridge",
   "State": "MA",
   "County": "Middlesex County",
   "Zip": 2139,
   "Country": "US",
   "Source": "City of Cambridge"
 },
 {
   "Name": "Museum of the National Center of Afro-American Artists",
   "Address": "300 Walnut Ave Roxbury, MA 02119",
   "Neighborhood": "Roxbury",
   "Description": "Museum of the National Center of Afro-American Artists",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.316784,
   "Longitude": -71.092025,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": "300",
   "Street": "Walnut Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Martin Luther King Jr Residence",
   "Address": "397 Massachusetts Ave, Boston, MA 02115",
   "Neighborhood": "South End",
   "Description": "Martin Luther King Jr resided here. Only previous residence with a plaque commemorating his tenancy",
   "Link to Description": "https://boston.curbed.com/2016/1/11/10848190/martin-luther-king-jr-boston",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.341277,
   "Longitude": -71.083151,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": "397",
   "Street": "Massachusetts Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Martin Luther King Jr Residence",
   "Address": "170 St. Botolph Street, Boston, MA, 02115",
   "Neighborhood": "South End",
   "Description": "Martin Luther King Jr resided here.",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.342702,
   "Longitude": -71.083173,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": "170",
   "Street": "St Botolph St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2115,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Martin Luther King Jr Residence",
   "Address": "396 Northampton Street #5, Boston, MA 02118",
   "Neighborhood": "South End",
   "Description": "Martin Luther King Jr resided here in 1954. Likely first home after 1953 marriage to Coretta Scott",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.340568,
   "Longitude": -71.083841,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "396",
   "Street": "Northampton St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Martin Luther King Jr Residence",
   "Address": "21 Holyoke Street, Boston, MA 02116",
   "Neighborhood": "South End",
   "Description": "Martin Luther King Jr Residence",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.344967,
   "Longitude": -71.077871,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "21",
   "Street": "Holyoke St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2116,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "William E. Carter Playground",
   "Address": "369 Northampton Street, Roxbury, MA 02118",
   "Neighborhood": "South End",
   "Description": "First public park in Boston named for an African American. William E. Carter was a veteran of the Spanish-American War and WWI. MLK Jr. played baseball here while residing in Boston.",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.340463,
   "Longitude": -71.082773,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": "369",
   "Street": "Northampton St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Twelfth Baptist Church",
   "Address": "",
   "Neighborhood": "South End",
   "Description": "Formed in 1840 out of split from African Meeting House led by Reverend Black",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 0,
   "Longitude": 0,
   "Accuracy Score": 0,
   "Accuracy Type": "",
   "Number": "",
   "Street": "",
   "City": "",
   "State": "",
   "County": "",
   "Zip": null,
   "Country": "",
   "Source": ""
 },
 {
   "Name": "Twelfth Baptist Church (previous address)",
   "Address": "680 Shawmut Ave, Boston, MA 02119",
   "Neighborhood": "Roxbury",
   "Description": "MLK Jr preached here from 1951-1954",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.333929,
   "Longitude": -71.082218,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": "680",
   "Street": "Shawmut Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "League of Women for Community Service",
   "Address": "558 Massachusetts Ave, Boston, MA 02118",
   "Neighborhood": "South End",
   "Description": "Coretta Scott King  lived here while attending NEC",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.338249,
   "Longitude": -71.078342,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "558",
   "Street": "Massachusetts Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Maud Cuney Hare Home",
   "Address": "43 Sheridan Street, Jamaica Plain, MA 02130",
   "Neighborhood": "Jamaica Plain",
   "Description": "Home of Maud Cuney Hare, multi-talented musician, artist, piano-lecturer, composer, playwright, biographer, Black-music historian and collector. Founder of The Allied Arts Center in Boston.",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.320837,
   "Longitude": -71.107771,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "43",
   "Street": "Sheridan St",
   "City": "Jamaica Plain",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2130,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Justice Edward Orval Gourdin Veterans Memorial Park",
   "Address": "2405 Washington Street, Roxbury, MA 02119",
   "Neighborhood": "Roxbury",
   "Description": "Justice Edward Orval Gourdin Veterans Memorial Park",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.328848,
   "Longitude": -71.085823,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": "2405",
   "Street": "Washington St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Harriet Tubman Square",
   "Address": "450 Columbus Ave, Boston, MA 02116",
   "Neighborhood": "South End",
   "Description": "Vietnam Veteran. ",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.343778,
   "Longitude": -71.07748,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": "450",
   "Street": "Columbus Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2116,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "David L. Ramsay Park",
   "Address": "199 Ball Street, Roxbury, MA 02119",
   "Neighborhood": "Roxbury",
   "Description": "David L. Ramsay Park",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.317878,
   "Longitude": -71.078017,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": "199",
   "Street": "Blue Hill Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Jim Rice Field",
   "Address": "199 Ball Street, Roxbury, MA 02119",
   "Neighborhood": "Roxbury",
   "Description": "Jim Rice Field",
   "Link to Description": "",
   "Link to Image": "",
   "Additional Resources": "",
   "Latitude": 42.317878,
   "Longitude": -71.078017,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": "199",
   "Street": "Blue Hill Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
  {
   "Name": "Darryl's Corner Bar and Kitchen",
   "Address": "604 Columbus Ave, Boston, Ma",
   "Neighborhood": "South End",
   "Description": "BBQ Joint",
   "Website": "http://dcbkboston.com/",
   "Additional Info": "",
   "Latitude": 42.339767,
   "Longitude": -71.0824,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 604,
   "Street": "Columbus Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Teranga Restaurant",
   "Address": "1746 Washington Street, Boston, Ma",
   "Neighborhood": "South End",
   "Description": "African Food",
   "Website": "http://terangaboston.com/",
   "Additional Info": "",
   "Latitude": 42.336477,
   "Longitude": -71.076531,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 1746,
   "Street": "Washington St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "La Fabrica Central",
   "Address": "450 Massachusetts Ave, Cambridge, Ma",
   "Neighborhood": "Cambridge",
   "Description": "Caribbean Food",
   "Website": "https://www.lafabricacentral.com/",
   "Additional Info": "",
   "Latitude": 42.363484,
   "Longitude": -71.101101,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 450,
   "Street": "Massachusetts Ave",
   "City": "Cambridge",
   "State": "MA",
   "County": "Middlesex County",
   "Zip": 2139,
   "Country": "US",
   "Source": "City of Cambridge"
 },
 {
   "Name": "Savvor Restaurant",
   "Address": "180 Lincoln Street, Boston, MA 02111",
   "Neighborhood": "Finance District",
   "Description": "Haitian",
   "Website": "https://www.savvorbostonlounge.com/",
   "Additional Info": "",
   "Latitude": 42.350537,
   "Longitude": -71.058441,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 180,
   "Street": "Lincoln St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2111,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Restaurante Cesaria",
   "Address": "266 Bowdoin Street, Boston, Ma",
   "Neighborhood": "North Dorchester",
   "Description": "Cape Verdean/African",
   "Website": "https://www.facebook.com/RestaurantCesaria/",
   "Additional Info": "",
   "Latitude": 42.30692,
   "Longitude": -71.06667,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 266,
   "Street": "Bowdoin St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2125,
   "Country": "US",
   "Source": "City of Boston"
 },
 {
   "Name": "Restaurant Laura",
   "Address": "688 Columbia Rd, Dorchester, MA 02125",
   "Neighborhood": "North Dorchester",
   "Description": "Cape Verdean/African",
   "Website": "https://www.facebook.com/pages/category/Family-Style-Restaurant/Restaurant-Laura-347785340882/",
   "Additional Info": "",
   "Latitude": 42.320097,
   "Longitude": -71.062641,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 688,
   "Street": "Columbia Rd",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2125,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "BRED",
   "Address": "2255 Dorchester Ave Boston, MA 02124",
   "Neighborhood": "South Dorchester",
   "Description": "Burger Joint",
   "Website": "http://www.bredgourmet.com/",
   "Additional Info": "",
   "Latitude": 42.273407,
   "Longitude": -71.067951,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 2255,
   "Street": "Dorchester Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2124,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "ZAZ Restaurant",
   "Address": "1238 River St, Hyde Park, MA 02136",
   "Neighborhood": "Hyde Park",
   "Description": "Caribbean",
   "Website": "http://www.zazrestaurant.com/",
   "Additional Info": "",
   "Latitude": 42.255807,
   "Longitude": -71.122991,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 1238,
   "Street": "River St",
   "City": "Hyde Park",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2136,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "MIDA Restaurant",
   "Address": "782 Tremont St, Boston, MA 02118",
   "Neighborhood": "South End",
   "Description": "Italian",
   "Website": "http://www.midaboston.com",
   "Additional Info": "",
   "Latitude": 42.339047,
   "Longitude": -71.080431,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 782,
   "Street": "Tremont St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Churrascaria Vulcão",
   "Address": "203 Adams St, Boston, MA 02122",
   "Neighborhood": "South Dorchester",
   "Description": "Cape Verdean/Portuguese",
   "Website": "http://www.churrascariavulcao.com/",
   "Additional Info": "",
   "Latitude": 42.301898,
   "Longitude": -71.060211,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 203,
   "Street": "Adams St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2122,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Fort Hill Bar & Grill",
   "Address": "2805 Washington St, Boston, MA 02119",
   "Neighborhood": "Roxbury",
   "Description": "Dominican/American",
   "Website": "https://www.facebook.com/forthillbarandgrill/",
   "Additional Info": "",
   "Latitude": 42.321426,
   "Longitude": -71.092089,
   "Accuracy Score": 1,
   "Accuracy Type": "range_interpolation",
   "Number": 2805,
   "Street": "Washington St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "TIGER/Line® dataset from the US Census Bureau"
 },
 {
   "Name": "Suyya Joint",
   "Address": "185 Dudley St #2, Roxbury, MA 02119",
   "Neighborhood": "Roxbury",
   "Description": "Nigerian ",
   "Website": "https://suyajoint.com/",
   "Additional Info": "",
   "Latitude": 42.32832,
   "Longitude": -71.08196,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 185,
   "Street": "Dudley St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "City of Boston"
 },
 {
   "Name": "Dona Habana",
   "Address": "811 Massachusetts Ave, Boston, MA 02118",
   "Neighborhood": "South End",
   "Description": "Cuban",
   "Website": "http://donahabanarestaurant.com/",
   "Additional Info": "",
   "Latitude": 42.332703,
   "Longitude": -71.072923,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": 811,
   "Street": "Massachusetts Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Addis Red Sea",
   "Address": "544 Tremont St, Boston, MA 02116",
   "Neighborhood": "South End",
   "Description": "Ethiopian",
   "Website": "http://www.addisredsea.com/",
   "Additional Info": "",
   "Latitude": 42.344027,
   "Longitude": -71.071051,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": 544,
   "Street": "Tremont St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "The Coast Cafe",
   "Address": "233 River St, Cambridge, MA 02139",
   "Neighborhood": "Cambridge",
   "Description": "South American",
   "Website": "http://www.coastsoulcafe.com/",
   "Additional Info": "",
   "Latitude": 42.363012,
   "Longitude": -71.111597,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 233,
   "Street": "River St",
   "City": "Cambridge",
   "State": "MA",
   "County": "Middlesex County",
   "Zip": 2139,
   "Country": "US",
   "Source": "City of Cambridge"
 },
 {
   "Name": "Wally's Jazz Cafe",
   "Address": "427 Massachusetts Ave, Boston, MA 02118",
   "Neighborhood": "South End",
   "Description": "Jazz Bar",
   "Website": "http://wallyscafe.com/",
   "Additional Info": "",
   "Latitude": 42.340697,
   "Longitude": -71.082291,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 427,
   "Street": "Massachusetts Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2118,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Slade's Bar and Grille ",
   "Address": "958 Tremont St, Boston, MA 02120",
   "Neighborhood": "South End",
   "Description": "Southern ",
   "Website": "https://www.sladesbarandgrill.com/",
   "Additional Info": "",
   "Latitude": 42.337256,
   "Longitude": -71.083617,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 958,
   "Street": "Tremont St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2120,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Rock CIty Pizza",
   "Address": "568 Cambridge St, Allston, MA 02134",
   "Neighborhood": "Allston",
   "Description": "Pizzeria",
   "Website": "https://rockcitypizzeria.com/",
   "Additional Info": "",
   "Latitude": 42.352312,
   "Longitude": -71.14044,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 568,
   "Street": "Cambridge St",
   "City": "Allston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2134,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Ashur Restaurant",
   "Address": "291 Roxbury St, Roxbury, MA 02119",
   "Neighborhood": "Roxbury",
   "Description": "Somali",
   "Website": "https://www.bostonmagazine.com/best-of-boston/2015/ashur-restaurant/",
   "Additional Info": "",
   "Latitude": 42.330427,
   "Longitude": -71.094301,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 291,
   "Street": "Roxbury St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2119,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Asmara Restaurant",
   "Address": "739 Massachusetts Ave, Cambridge, MA 02139",
   "Neighborhood": "Cambridge",
   "Description": "Ethiopian",
   "Website": "http://www.asmararestaurantboston.com/",
   "Additional Info": "",
   "Latitude": 42.366458,
   "Longitude": -71.105164,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 739,
   "Street": "Massachusetts Ave",
   "City": "Cambridge",
   "State": "MA",
   "County": "Middlesex County",
   "Zip": 2139,
   "Country": "US",
   "Source": "City of Cambridge"
 },
 {
   "Name": "Flames",
   "Address": "469 Blue Hill Avenue, Dorchester, MA 02121",
   "Neighborhood": "Dorchester-Grove Hall",
   "Description": "Jamaican",
   "Website": "",
   "Additional Info": "",
   "Latitude": 42.309036,
   "Longitude": -71.083258,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 469,
   "Street": "Blue Hill Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2121,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "Flames II",
   "Address": "746 Huntington Ave, Boston, MA 02115",
   "Neighborhood": "Mission Hill",
   "Description": "Jamaican",
   "Website": "https://www.zagat.com/r/flames-restaurant-inc-boston1",
   "Additional Info": "",
   "Latitude": 42.333647,
   "Longitude": -71.105491,
   "Accuracy Score": 0.9,
   "Accuracy Type": "rooftop",
   "Number": 746,
   "Street": "Huntington Ave",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2120,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 },
 {
   "Name": "The Beehive",
   "Address": "541 Tremont St, Boston, MA 02116",
   "Neighborhood": "South End",
   "Description": "American",
   "Website": "https://www.beehiveboston.com/",
   "Additional Info": "",
   "Latitude": 42.344716,
   "Longitude": -71.071388,
   "Accuracy Score": 1,
   "Accuracy Type": "rooftop",
   "Number": 541,
   "Street": "Tremont St",
   "City": "Boston",
   "State": "MA",
   "County": "Suffolk County",
   "Zip": 2116,
   "Country": "US",
   "Source": "Office of Geographic Information (MassGIS), Commonwealth of Massachusetts, MassIT"
 }
]


